apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-allow-from-web
  namespace: tankrank
spec:
  podSelector:
    matchLabels:
      app: tank-rating-api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: tank-rating-web
