apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: tank-rating-api
    app.kubernetes.io/component: tank-rating-api
    app.kubernetes.io/instance: tank-rating-api
  name: tank-rating-api
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: tank-rating-api:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: tankrank
      uri: https://github.com/mandibuswell/mslearn-aks-workshop-ratings-api
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:16-ubi8
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: YayIY_hISiuaEDqvtkuj
    type: GitHub
  - generic:
      secret: rcnQ4xEWraFv3_EPw__X
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
