apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    openshift.io/image.dockerRepositoryCheck: "2024-03-21T01:35:31Z"
  labels:
    app: rating-api
    app.kubernetes.io/component: rating-api
    app.kubernetes.io/instance: rating-api
  name: rating-api
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: rating-api:latest
    generation: 3
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source
